spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EmployeeProject
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver  
  jpa: 
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/EmployeeProject
    schemas: EmployeeProject
    user: "root" 
    password: "root"
   
logging:
  file:
    name: "app.log"
  logback:
    rollingpolicy:
      file-name-pattern: app-%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      max-history: 50
      total-size-cap: 10MB
  level:
    root: info
        
server:
  port: 8082